version: '3.8'

services:
  dev.gateway:
    container_name: nestjs_gateway_api_dev
    image: nestjs-api-dev:1.1.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: nest start gateway --watch
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - /docker-volumes/gateway
    restart: unless-stopped
  dev.image-handler:
    container_name: nestjs_image_handler_api_dev
    image: nestjs-api-dev:1.1.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command:  nest start image-handler --watch
    ports:
      - 3001:3001
      - 9239:9239
    networks:
      - nesjs-network
    volumes:
      - /docker-volumes/image-handler
    restart: unless-stopped
networks:
  nesjs-network:







