version: '3.8'

services:
  dev.gateway:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: concurrently --kill-others "nest start gateway --watch" "nest start image-handler --watch"
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - apps/gateway
    restart: unless-stopped
networks:
  nesjs-network: